import { Metadata } from 'next';
import { Geist, Geist_Mono } from 'next/font/google';

import { i18n, type Locale } from '@/lib/i18n.config';
import { getDictionary } from '@/lib/dictionary';
import Header from '@/components/Header/Header';
import Footer from '@/components/Footer/Footer';
import '../globals.css';

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
});

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
});

export async function generateStaticParams() {
  return i18n.locales.map((locale) => ({ locale }));
}

export async function generateMetadata({
  params,
}: {
  params: Promise<{ locale: Locale }>;
}): Promise<Metadata> {
  const { locale } = await params;

  return {
    title: locale === 'de' ? 'Globuss Lösungen' : 'Globuss Solutions',
    description:
      locale === 'de'
        ? 'Generiert von create next app'
        : 'Generated by create next app',
  };
}

interface LocaleLayoutProps {
  children: React.ReactNode;
  params: Promise<{ locale: string }>;
}

export default async function LocaleLayout({
  children,
  params,
}: LocaleLayoutProps) {
  const { locale } = await params;
  const dict = await getDictionary(locale as Locale);

  return (
    <html lang={locale}>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Header locale={locale as Locale} dict={dict} />
        <main className="min-h-screen">{children}</main>
        <Footer locale={locale as Locale} dict={dict} />
      </body>
    </html>
  );
}
