import { Metadata } from 'next';
import { Geist, Geist_Mono } from 'next/font/google';

import { i18n, type Locale } from '@/lib/i18n.config';
import { getDictionary } from '@/lib/dictionary';
import Header from '@/components/Header/Header';
import Footer from '@/components/Footer/Footer';

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
});

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
});

export async function generateStaticParams() {
  return i18n.locales.map((locale) => ({ locale }));
}

export async function generateMetadata({
  params,
}: {
  params: Promise<{ locale: string }>; // Change to string
}): Promise<Metadata> {
  const { locale } = await params;

  return {
    title: locale === 'de' ? 'Globuss Lösungen' : 'Globuss Solutions',
    description:
      locale === 'de'
        ? 'Generiert von create next app'
        : 'Generated by create next app',
  };
}

interface LocaleLayoutProps {
  children: React.ReactNode;
  params: Promise<{ locale: string }>; // Change to string to match Next.js types
}

export default async function LocaleLayout({
  children,
  params,
}: LocaleLayoutProps) {
  const { locale } = await params;
  // Cast to Locale here since we know it's valid due to generateStaticParams/middleware
  const typedLocale = locale as Locale;
  const dict = await getDictionary(typedLocale);

  return (
    <html
      lang={typedLocale}
      data-scroll-behavior="smooth"
      suppressHydrationWarning
    >
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Header locale={typedLocale} dict={dict} />
        <main className="min-h-screen">{children}</main>
        <Footer locale={typedLocale} dict={dict} />
      </body>
    </html>
  );
}
